package com.metadata.constant;

public class AlgorithmConstant {
    public static final String PROCESS_NETWORK = "ProcessNetwork";
    public static final String COMPUTATION_TASK = "Computational";
    public static final String CONTROL_TASK = "Control";
    public static final String YES = "Yes";
    public static final String NO = "No";
    public static final String TIME_DRIVEN = "time-driven";
    public static final String CONTROL_DRIVEN = "control-driven";
    public static final String DATA_DRIVEN = "data-driven";
    public static final String DEFAULT = "Default";
    public static final String DEFAULT_FILE = "task.xml";
    public static final String LANGUAGE_C = "C";
    public static final String LISTEN = "listen";
    public static final String REPORT = "report";
    public static final String CONTROL = "control";
    public static final String LEADER = "leader";
    public static final String GROUP = "group";
    public static final String ROBOT_ID = "robotId";
    public static final String HEARTBEAT = "heartbeat";
    public static final String EVENT = "event";

    public static final String LIBRARY_FILE_EXTENSION = ".cicl";
    public static final String LIBRARY_HEADER_EXTENSION = ".cicl.h";
    public static final String TASK_FILE_EXTENSION = ".cic";

    public static final String ROBOT_COMMON_HEADER_SUFFIX = "_common.h";
    public static final String ROBOT_PORT_HEADER_SUFFIX = "_port.h";
    public static final String ROBOT_VARIABLE_HEADER_SUFFIX = "_variable.h";
    public static final String ROBOT_PORT_SOURCE_SUFFIX = "_port.c";
    public static final String ROBOT_VARIABLE_SOURCE_SUFFIX = "_variable.c";
    public static final String ROBOT_EVENT_HEADER_SUFFIX = "_event.h";
    public static final String ROBOT_EVENT_SOURCE_SUFFIX = "_event.c";
    public static final String ROBOT_RESOURCE_HEADER_SUFFIX = "_resource.h";
    public static final String ROBOT_RESOURCE_SOURCE_SUFFIX = "_resource.c";
    public static final String ROBOT_ACTION_HEADER_SUFFIX = "_action.h";
    public static final String ROBOT_ACTION_SOURCE_SUFFIX = "_action.c";
    public static final String ROBOT_TRANSITION_HEADER_SUFFIX = "_transition.h";
    public static final String ROBOT_TRANSITION_SOURCE_SUFFIX = "_transition.c";
    public static final String ROBOT_TEAM_HEADER_SUFFIX = "_team.h";
    public static final String ROBOT_SERVICE_HEADER_SUFFIX = "_service.h";
    public static final String ROBOT_SERVICE_SOURCE_SUFFIX = "_service.c";
    public static final String ROBOT_TIMER_HEADER_SUFFIX = "_timer.h";
    public static final String ROBOT_TIMER_SOURCE_SUFFIX = "_timer.c";
    public static final String ROBOT_MODE_HEADER_SUFFIX = "_mode.h";
    public static final String ROBOT_MODE_SOURCE_SUFFIX = "_mode.c";
    public static final String ROBOT_GROUP_HEADER_SUFFIX = "_group.h";
    public static final String ROBOT_GROUP_SOURCE_SUFFIX = "_group.c";
    public static final String ROBOT_LEADER_LIBRARY_SOURCE_SUFFIX = "_leader_lib.cicl";
    public static final String ROBOT_LEADER_LIBRARY_HEADER_SUFFIX = "_leader_lib.cicl.h";
    public static final String COMMON_HEADER = "semo_common.h";
    public static final String LOGGER_HEADER = "semo_logger.h";
    public static final String COMMON_LEADER_HEADER = "semo_leader.h";
    public static final String COMMON_PORT_HEADER = "semo_port.h";
    public static final String COMMON_COMMUNICATION_HEADER = "semo_communication.h";
    public static final String COMMON_COMMUNICATION_SOURCE = "semo_communication.c";
    public static final String COMMON_VARIABLE_HEADER = "semo_variable.h";
    public static final String COMMON_VARIABLE_SOURCE = "semo_variable.c";
    public static final String MUTEX_HEADER = "UCThreadMutex.h";
    public static final int MULTICAST_PACKET_SIZE = 12;
}
